import os
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import markdown
import smtplib
from langchain_core.runnables import RunnableConfig

from state import NewsletterState

def publisher_node(state: NewsletterState, config: RunnableConfig):
    """
    This node takes the newsletter draft generated by the writer node, formats it as an email, and sends it to the specified recipient using SMTP.

    Parameters
    ----------
    state : NewsletterState
        The current state of the newsletter generation process, which includes the newsletter draft and other relevant information.
    config : RunnableConfig
        The configuration object that contains any necessary parameters for the publisher node, such as email credentials and recipient information.

    Returns
    --------
    dict
        A dictionary containing the steps taken by the publisher node.
    """
    logging.info("Starting publisher node ...")
    # Fetching environment variables set in GitHub Secrets
    configurable = config.get("configurable", {})
    sender = configurable.get("SENDER_EMAIL", None)
    pw = configurable.get("SENDER_PASSWORD", None)
    receiver = configurable.get("RECEIVER_EMAIL", None)
    html = markdown.markdown(state['newsletter_draft'])
    msg = MIMEMultipart()
    msg['Subject'] = f"📊 DS Pulse: {state['topic']} - {state['subtopic']}"
    msg['From'] = sender
    msg['To'] = receiver
    msg.attach(MIMEText(f"<html><body>{html}</body></html>", 'html'))
    logging.info("Sending email via SMTP ...")
    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(sender, pw)
        server.send_message(msg)
    return {"steps_taken": ["publisher_complete"]}